// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	AdminID         pgtype.UUID      `json:"admin_id"`
	FirstName       string           `json:"first_name"`
	LastName        string           `json:"last_name"`
	Email           string           `json:"email"`
	Password        string           `json:"password"`
	ProfileImageUrl pgtype.Text      `json:"profile_image_url"`
	JoinedAt        pgtype.Timestamp `json:"joined_at"`
}

type Course struct {
	CourseID        pgtype.UUID      `json:"course_id"`
	LanguageID      pgtype.Int4      `json:"language_id"`
	CourseName      string           `json:"course_name"`
	DifficultyLevel pgtype.Text      `json:"difficulty_level"`
	IsFree          pgtype.Bool      `json:"is_free"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Exercise struct {
	ExerciseID    pgtype.UUID `json:"exercise_id"`
	LessonID      pgtype.Int4 `json:"lesson_id"`
	ExerciseType  pgtype.Text `json:"exercise_type"`
	QuestionText  string      `json:"question_text"`
	CorrectAnswer string      `json:"correct_answer"`
	Options       []byte      `json:"options"`
	AudioUrl      pgtype.Text `json:"audio_url"`
}

type Language struct {
	LanguageID   pgtype.UUID `json:"language_id"`
	LanguageName string      `json:"language_name"`
	LanguageCode string      `json:"language_code"`
	FlagEmoji    pgtype.Text `json:"flag_emoji"`
	Description  pgtype.Text `json:"description"`
}

type Lesson struct {
	LessonID    pgtype.UUID `json:"lesson_id"`
	CourseID    pgtype.Int4 `json:"course_id"`
	LessonTitle string      `json:"lesson_title"`
	LessonOrder int32       `json:"lesson_order"`
	XpReward    pgtype.Int4 `json:"xp_reward"`
	IsUnlocked  pgtype.Bool `json:"is_unlocked"`
}

type User struct {
	UserID          pgtype.UUID      `json:"user_id"`
	Username        string           `json:"username"`
	Email           string           `json:"email"`
	Password        string           `json:"password"`
	ProfileImageUrl pgtype.Text      `json:"profile_image_url"`
	StreakCount     pgtype.Int4      `json:"streak_count"`
	XpPoints        pgtype.Int4      `json:"xp_points"`
	LastActiveDate  pgtype.Timestamp `json:"last_active_date"`
	JoinedAt        pgtype.Timestamp `json:"joined_at"`
}

type UserCourse struct {
	UserCourseID         pgtype.UUID      `json:"user_course_id"`
	UserID               pgtype.Int4      `json:"user_id"`
	CourseID             pgtype.Int4      `json:"course_id"`
	EnrollmentDate       pgtype.Timestamp `json:"enrollment_date"`
	CompletionPercentage pgtype.Float8    `json:"completion_percentage"`
}

type UserProgress struct {
	ProgressID  pgtype.UUID      `json:"progress_id"`
	UserID      pgtype.Int4      `json:"user_id"`
	LessonID    pgtype.Int4      `json:"lesson_id"`
	ExerciseID  pgtype.Int4      `json:"exercise_id"`
	IsCompleted pgtype.Bool      `json:"is_completed"`
	Score       pgtype.Int4      `json:"score"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}
