// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	DeleteAdmin(ctx context.Context, adminID pgtype.UUID) error
	GetAdminByEmail(ctx context.Context, email string) (GetAdminByEmailRow, error)
	GetAdminById(ctx context.Context, adminID pgtype.UUID) (GetAdminByIdRow, error)
	GetAdminForLogin(ctx context.Context, email string) (GetAdminForLoginRow, error)
	GetAllAdmins(ctx context.Context, arg GetAllAdminsParams) ([]GetAllAdminsRow, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) error
}

var _ Querier = (*Queries)(nil)
